### ISSUE TITLE
can't install gocv

### ISSUE THREAD

**Issue by Eghbalii** [hybridgroup/gocv#550]
try to install with command:  go get -u -d gocv.io/x/gocv
## Description

it passed without any problem. but there is no file or directory in Go/src  "gocv.io"
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Operating System and version:win10
* OpenCV version used:
* How did you install OpenCV?
* GoCV version used:
* Go version:
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?

**Comment by linkerlin** [comment]
> try to install with command: go get -u -d gocv.io/x/gocv
> 
> ## Description
> it passed without any problem. but there is no file or directory in Go/src "gocv.io"
> 
> ## Steps to Reproduce
> 
> ## Your Environment
> * Operating System and version:win10
> * OpenCV version used:
> * How did you install OpenCV?
> * GoCV version used:
> * Go version:
> * Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?

Install opencv4 for windows firstly

**Comment by Eghbalii** [comment]
I actually did it and also install opencv with cmake on minGW.

**Comment by yunholeeme** [comment]
![image](https://user-images.githubusercontent.com/12512309/70789878-3a35cd00-1dd7-11ea-97aa-bbd2b1e09ac6.png)

this command will help you.

**Comment by deadprogram** [comment]
This issue seems like it was solved? If not, then please reopen. Thank you!

**Comment by BryceWayne** [comment]
Still won't install gocv with the instructions provided on site

**Comment by chrispump** [comment]
> Still won't install gocv with the instructions provided on site

try manually downloading the repository, put it into your `%GOPATH%/src` and run `win_build_opencv.cmd` as mentioned.
you might need to add `C:\opencv\build\install\x64\mingw\bin` to your environment variables and fire `go get gocv.io/x/gocv` after.

dirty but worked for me.
